/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    ReferralContract: {
      address:
        "0x1e618caa4c5286454917bd3a7cae4fcf6d41241f01777a514a625bd1122f7f4",
      abi: [
        {
          type: "impl",
          name: "ReferralContractImpl",
          interface_name: "contracts::ReferralContract::IReferralContract",
        },
        {
          type: "interface",
          name: "contracts::ReferralContract::IReferralContract",
          items: [
            {
              type: "function",
              name: "generate_referral_code",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::ReferralContract::ReferralContract::ReferralCodeGenerated",
          kind: "struct",
          members: [
            {
              name: "referrer",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "code",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::ReferralContract::ReferralContract::Event",
          kind: "enum",
          variants: [
            {
              name: "ReferralCodeGenerated",
              type: "contracts::ReferralContract::ReferralContract::ReferralCodeGenerated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x4e886d58f0b0d2b6483ee4b85a055588cff7a09a467b6c89cacca19b3f74ebb",
    },
  },
} as const;

export default deployedContracts;
